language: python

python:
  - "3.7"

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install scipy
  - python setup.py develop

script:
  - pytest -v tests/ --cov=KeplerOrbit/

after_success:
  - bash <(curl -s https://codecov.io/bash)